[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ltc"
version = "0.1.0"
requires-python = ">=3.12, <4"

description = "Learning to communicate"
readme = "README.md"
license = { file = "LICENSE" }
keywords = ["machine-learning", "reinforcement-learning", "jax", "wireless-communication", "multi-agent-systems"]

authors = [
  {name = "Maksymilian Wojnar", email = "maksymilian.wojnar@agh.edu.pl"},
  {name = "Kamil Szczęch", email = "kamil.szczech@agh.edu.pl"},
  {name = "Krzysztof Rusek", email = "krzysztof.rusek@agh.edu.pl"},
  {name = "Katarzyna Kosek-Szott", email = "katarzyna.kosek-szott@agh.edu.pl"},
  {name = "Szymon Szott", email = "szymon.szott@agh.edu.pl"}
]

dependencies = [
    "jax-tqdm==0.4.0",
    "reinforced-lib==2.0.0",
    "tqdm~=4.67.1",
]

[project.optional-dependencies]
gpu = [
    "jax[cuda12-local]",
]
notebook = [
    "jupyterlab~=4.4.9",
    "seaborn~=0.13.2",
]

[tool.setuptools]
packages = ["ltc"]
