from enum import Enum


class Actions(Enum):
    """
    Actions for the agent
    """
    TX = 0
    CS = 1
    IDLE = 2


"""
Simulation parameters
"""
MAX_RETRANSMISSION = 8
SAFE_IDLE_PERIOD = 25
SAFE_IDLE_PERIOD_STD = 3
PENALIZED_IDLE_PERIOD = 25

"""
Rewards and penalties
"""
TX_REWARD = 1.0
EMPTY_BUFFER_REWARD = 0.5
NO_TX_REWARD = 0.0
NO_TX_PENALTY = -1.0
EMPTY_TX_PENALTY = -0.5
COLLISION_PENALTY = -1.0
MAX_RETRANSMISSION_PENALTY = -1.0

TX_REWARD_LENGTH = 5
TX_SIZE_THRESHOLD = 5
TX_SIZE_PENALTY_WINDOW = 25
TX_SIZE_PENALTY = -1.0
TX_LTC_COLLISION_PENALTY = -1.0
TX_COEX_COLLISION_PENALTY = -5.0
TX_EMPTY_BUFFER_PENALTY = EMPTY_TX_PENALTY
TX_MAX_RETRANSMISSION_PENALTY = MAX_RETRANSMISSION_PENALTY

"""
Power consumption
"""
INITIAL_CAPACITY = int(1e9)
TX_CONSUMPTION = 5
CS_CONSUMPTION = 1
IDLE_CONSUMPTION = 0

"""
Tx slot duration (s)
https://ieeexplore.ieee.org/document/8930559
"""
TAU = 5.484 * 1e-3

# Queue representation
EMPTY_PACKET_ID = -1

"""
Macro-action defaults
"""
MAX_MACRO_DURATION = 5
LEGACY_TX_DURATION = 5

"""
Time scaling: one TX slot occupies TX_SLOTS mini-slots.
During one TX, CS agents can observe TX_SLOTS times.
"""
TX_SLOTS = 3


class ObsIdx:
    BUFFER_OCCUPANCY_PCT = 0
    BUFFER_PACKET_COUNT = 1
    BUFFER_OLDEST_AGE_NORM = 2
    TRAFFIC_MEAN_ARRIVAL_RATE = 3
    CHANNEL_LAST_CS_BUSY = 4
    CHANNEL_LAST_CS_TX_SAME_TYPE = 5
    CHANNEL_LAST_TX_COLLISION_OTHER = 6
    CHANNEL_OCCUPANCY_PCT_WINDOW = 7
    CHANNEL_COLLISIONS_PCT_WINDOW = 8
    ACTION_LAST = 9
    ACTION_BACK_PCT = 10
    STATUS_RETRY_COUNTER = 11
    STATUS_NO_TX_COUNTER = 12
    STATUS_UNIQUE_LTC_TX_WINDOW = 13


OBS_SIZE = 14
