"""
Simulation parameters
"""
MAX_RETRANSMISSION = 8
MAX_NO_TX_WITHOUT_PENALTY = 5
NO_TX_WITHOUT_MAX_PENALTY = 10
MAX_NO_TX_WITH_PENALTY = 15
TX_REWARD = 1.0
SHORT_NO_TX_REWARD = 0.0
LONG_NO_TX_REWARD = -0.9
MAX_NO_TX_REWARD = -1.0
EMPTY_TX_PENALTY = -0.5
COLLISION_PENALTY = -1.0
MAX_RETRANSMISSION_PENALTY = -1.0

"""
Tx slot duration (s)
https://ieeexplore.ieee.org/document/8930559
"""
TAU = 5.484 * 1e-3
