class ObsIdx:
    BUFFER_OCCUPANCY_PCT = 0
    BUFFER_PACKET_COUNT = 1
    BUFFER_OLDEST_AGE_NORM = 2
    TRAFFIC_MEAN_ARRIVAL_RATE = 3
    CHANNEL_LAST_CS_BUSY = 4
    CHANNEL_LAST_CS_TX_SAME_TYPE = 5
    CHANNEL_LAST_TX_COLLISION_OTHER = 6
    CHANNEL_OCCUPANCY_PCT_WINDOW = 7
    CHANNEL_COLLISIONS_PCT_WINDOW = 8
    ACTION_LAST = 9
    ACTION_BACK_PCT = 10
    STATUS_RETRY_COUNTER = 11
    STATUS_NO_TX_COUNTER = 12
    STATUS_UNIQUE_LTC_TX_WINDOW = 13


OBS_SIZE = 14
